"use client"; // This directive indicates that this file contains client-side code.

import type { Metadata } from "next"; // Importing the type definition for Metadata from the Next.js library.
import { Inter } from "next/font/google"; // Importing the Inter font from Google Fonts using Next.js.
import "./globals.css"; // Importing global CSS styles.
import StyledComponentsRegistry from "../lib/registry"; // Importing the Styled Components registry for managing styles.
import { useEffect, useState } from "react"; // Importing the useState hook from React for state management.

// Initializing the Inter font with the Latin subset.
const inter = Inter({ subsets: ["latin"] });

// Defining metadata for the application.
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component that serves as the layout for the entire application.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  // Returning the HTML structure of the layout.
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrapping children components with StyledComponentsRegistry for style management. */}
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
